//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_HelpDesk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentID { get; set; }
        public int requestID { get; set; }
        public Nullable<int> userID { get; set; }
        public bool isSystem { get; set; }
        public Nullable<int> eventID { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public bool isEdited { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
    
        public virtual CommentEvent CommentEvent { get; set; }
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
    }
}
