//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_HelpDesk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notificationID { get; set; }
        public int userID { get; set; }
        public int notificationStatusID { get; set; }
        public int templateID { get; set; }
        public Nullable<int> initiatorID { get; set; }
        public Nullable<int> requestID { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public bool isRead { get; set; }
    
        public virtual User User { get; set; }
        public virtual NotificationStatus NotificationStatus { get; set; }
        public virtual Request Request { get; set; }
        public virtual User User1 { get; set; }
        public virtual NotificationTemplate NotificationTemplate { get; set; }
    }
}
