//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_HelpDesk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Comments = new HashSet<Comment>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int requestID { get; set; }
        public int clientID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int requestStatusID { get; set; }
        public int requestCategoryID { get; set; }
        public Nullable<int> workerID { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public Nullable<int> updatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual RequestCategory RequestCategory { get; set; }
        public virtual User User { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
